data:
   ko:
       rep1: $RNAMODBENCH_LOCAL/raw/result/xpore/HeLa_IVT_rep2_transcripts
   wt:
       rep1: $RNAMODBENCH_LOCAL/raw/result/xpore/HeLa_IVT_rep3_transcripts
out: $RNAMODBENCH_LOCAL/raw/result/xpore/HeLa_IVTresult3
criteria:
   readcount_min: 5
   readcount_max: 2000000