data:
   ko:
       rep1: $RNAMODBENCH_LOCAL/raw/result/xPore/E_IVT_neg1_transcripts
   wt:
       rep1: $RNAMODBENCH_LOCAL/raw/result/xPore/E_ss_rd_RNA1_transcripts
out: $RNAMODBENCH_LOCAL/raw/result/xPore/E_ss_rd_RNA1_result
criteria:
   readcount_min: 20
   readcount_max: 2000000