#!/usr/bin/env python
"""Figure S2 v4 - assemble A (full width), B (full width), C + D (side by side).

Same panel functions as the separate panel files, placed at their page slots,
so the assembled page is identical to the panel PDFs (no rescaling).  Page
size stays 595.276 x 653.256 pts (the published sup2 page).

Outputs figures/FigureS2_rev.{pdf,png}, figures/FigS2_legends_v4.md,
        logs/figS2v4_assemble_<date>.log
"""
from __future__ import annotations

import importlib.util
import sys
from datetime import date
from pathlib import Path

import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
FIG, LOGS = ROOT / "figures", ROOT / "logs"
spec = importlib.util.spec_from_file_location("s2v4", HERE / "09_figS2v4_panels.py")
P = importlib.util.module_from_spec(spec)
spec.loader.exec_module(P)


def main() -> None:
    P.apply_style()
    FIG.mkdir(parents=True, exist_ok=True)
    LOGS.mkdir(parents=True, exist_ok=True)
    pooled, top5, pwm, agac = P.load_inputs()
    over, summ = P.load_v4()
    h = P.panel_heights()

    y_a = 0.12
    y_b = y_a + h["A"] + 0.10
    y_cd = y_b + h["B"] + 0.12
    x_c, x_d, x_e = 0.18, 2.86, 5.62
    w_c, w_d, w_e = 2.54, 2.62, 2.48
    assert y_cd + max(h["C"], h["D"]) + 0.20 <= P.PAGE_H + 1e-9, "page overflow"

    fig = plt.figure(figsize=(P.PAGE_W, P.PAGE_H))
    P.draw_a(fig, pooled, pwm, org=(0.0, y_a))
    P.draw_b(fig, top5, org=(0.0, y_b))
    P.draw_c(fig, over, summ, org=(x_c, y_cd), panel_w=w_c)
    P.draw_d(fig, agac, org=(x_d, y_cd), panel_w=w_d)
    P.draw_e(fig, org=(x_e, y_cd), panel_w=w_e)
    # shared species legend for the lower row (once, centred)
    leg_y = (y_cd + max(h["C"], h["D"], h["E"]) + 0.16) / P.PAGE_H
    lx = 0.18 + 2.9
    leg = fig.add_axes([0, 0, 1, 1], zorder=0)
    leg.set_xlim(0, P.PAGE_W)
    leg.set_ylim(P.PAGE_H, 0)
    leg.axis("off")
    # markers, not colour bars: the key is the only place the species shapes are
    # defined, and panel D encodes the species by shape as well as colour
    for sp, col in (("Arabidopsis", P.INK["blue"]), ("Mouse", P.INK["orange"]),
                    ("Human", "#4D4D4D")):
        leg.scatter([lx], [leg_y * P.PAGE_H - 0.02], s=22, color=col,
                    marker=P.SP_MARKER[sp], edgecolor="white", linewidth=0.4,
                    zorder=3)
        leg.text(lx + 0.10, leg_y * P.PAGE_H - 0.02, sp, ha="left",
                 va="center", fontsize=P.FS["note"], color=P.INK["dark"])
        lx += 0.10 + 0.075 * len(sp) + 0.30
    smallest = P.assert_fonts(fig)
    stem = FIG / "FigureS2_rev"
    fig.savefig(str(stem) + ".pdf", bbox_inches=None)
    fig.savefig(str(stem) + ".png", dpi=300, bbox_inches=None)
    plt.close(fig)

    var = __import__("pandas").read_csv(ROOT / "analysis/figS2v4_variance.tsv",
                                        sep="\t")
    v = var[(var.scope == "cell means, panel-A 10 tools, three species")]
    tool_eta = float(v[v.Source == "Tool"].eta_sq.iloc[0]) * 100
    sp_eta = float(v[v.Source == "Species"].eta_sq.iloc[0]) * 100
    f_tool = float(v[v.Source == "Tool"].F.iloc[0])
    p_tool = float(v[v.Source == "Tool"].p.iloc[0])
    s4 = summ[summ.scope == "all four species"].iloc[0]
    note = (f"page {P.PAGE_W:.4f} x {P.PAGE_H:.4f} in (595.276 x 653.256 pts)\n"
            f"slots: A y={y_a:.2f} h={h['A']:.3f} | B y={y_b:.2f} "
            f"h={h['B']:.3f} | C/D y={y_cd:.2f} h={h['C']:.3f}/{h['D']:.3f}\n"
            f"smallest text {smallest:.2f} pt\n"
            f"KL variance (cell means, 10 tools x 3 species): tool "
            f"{tool_eta:.1f}% (F = {f_tool:.1f}, p = {p_tool:.1e}), "
            f"species {sp_eta:.1f}%\n"
            f"top-5 overlap (four species): within-species tools median "
            f"{s4.median_within:.1f} (n = {int(s4.n_within_species_pairs)}), "
            f"same tool across species median {s4.median_across:.1f} "
            f"(n = {int(s4.n_same_tool_pairs)}), Mann-Whitney one-sided "
            f"p = {s4.p_one_sided_less:.2e}")
    print(note)
    (LOGS / f"figS2v4_assemble_{date.today():%Y%m%d}.log").write_text(note + "\n")

    L = ["# Figure S2 (revision v4) - legend notes", "",
         "Generated by `scripts/08_figS2v4_stats.py` (statistics), "
         "`09_figS2v4_panels.py` (panels) and `10_figS2v4_assemble.py` "
         "(page).  Panels are also delivered separately under `figures/`.",
         "", "## Caption (paste into the Supporting Information)", "",
         "**Figure S2.** Detailed motif analysis of m6A detection tools and "
         "controls for tool-specific algorithmic bias (R3-6). (A) 5-mer "
         "sequence logos of the detected sites for the remaining 10 tools "
         "(mean KL divergence from the RRACH consensus next to each tool); the "
         "shared y-axis is the per-position information content in bits, "
         "computed on the replicate-equal-weight mean 5-mer probability matrix "
         "of each tool x species. (B) Top 5 preferred 5-mer motifs of each tool "
         "in four species; cell colour is the relative frequency of the 5-mer "
         f"(shared scale, 0-{P.VMAX:.2f}); RRACH 5-mers are shown in bold "
         "orange. (C) Top-5 5-mer identity across tools and species: the five "
         "most frequent 5-mers of two tools in the same species overlap far "
         f"less (median {s4.median_within:.0f} of 5, n = "
         f"{int(s4.n_within_species_pairs)} tool pairs) than those of the same "
         f"tool in two species (median {s4.median_across:.0f} of 5, n = "
         f"{int(s4.n_same_tool_pairs)} pairs; Mann-Whitney one-sided "
         f"p = {s4.p_one_sided_less:.1e}), i.e. motif identity follows the tool "
         "rather than the species. (D) Within-tool difference between the "
         "frequencies of AGAC-type and GGAC-type 5-mers: positive values "
         "indicate the plant-type AGAC motif, negative values the animal-type "
         "GGAC motif (Arabidopsis 12/13 tools positive; human 13/13 and mouse "
         "11/13 negative). The direction is systematic but small: a two-way "
         "decomposition of the KL divergence assigns "
         f"{tool_eta:.0f}% of the variance to the tool factor versus "
         f"{sp_eta:.0f}% to the species factor "
         f"(F = {f_tool:.1f}, p = {p_tool:.1e}), so these motif differences "
         "characterise the tools rather than species biology.", "",
         "## Statistics (computed in this project, 2026-09-21)", "",
         f"* KL variance decomposition, cell means of the 10 panel-A tools x 3 "
         f"species: tool {tool_eta:.1f}%, species {sp_eta:.1f}% "
         f"(F = {f_tool:.1f}, p = {p_tool:.1e}). Full 13-tool and per-unit "
         "variants: `analysis/figS2v4_variance.tsv`.",
         f"* Top-5 overlap, all four species: within-species tool pairs median "
         f"{s4.median_within:.1f} (n = {int(s4.n_within_species_pairs)}), "
         f"same-tool-across-species pairs median {s4.median_across:.1f} "
         f"(n = {int(s4.n_same_tool_pairs)}); Mann-Whitney one-sided "
         f"p = {s4.p_one_sided_less:.2e}, two-sided "
         f"p = {s4.p_two_sided:.2e} (`analysis/figS2v4_overlap.tsv`).",
         "* AGAC/GGAC counts and their assertion: "
         "`scripts/05_figS2_panelC_agac_inputs.py`.", ""]
    (FIG / "FigS2_legends_v4.md").write_text("\n".join(L))
    print("wrote", FIG / "FigS2_legends_v4.md")


if __name__ == "__main__":
    main()
